version: "3.9"

services:
  php:
    build:
      context: ./docker/php
    container_name: symfony-php
    working_dir: /var/www/html/project
    volumes:
      - ./:/var/www/html:cached
    environment:
      # Adjust as needed inside your Symfony .env
      APP_ENV: dev
      PHP_IDE_CONFIG: serverName=symfony-docker
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mariadb:11
    container_name: symfony-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
